name: OreRewards
main: com.techiecrow.OreRewards
description: give a random chance for a reward when breaking ores.
version: 1.0.0
author: TechieCrow

commands:
  orerewardsreload:
    description: Ore Rewards Reload Command

permissions:
  orerewards.reload:
    default: op